# Generated by Django 4.0.5 on 2022-06-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jardinesapp', '0002_categoria_alter_clientes_nombre_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(default='', max_length=40, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Telefono'),
        ),
    ]
