# Generated by Django 4.0.5 on 2022-07-14 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jardinesapp', '0005_productos_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pro', models.CharField(max_length=40, verbose_name='Nombre de producto')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca del Producto')),
                ('precio', models.IntegerField(null=True, verbose_name='Precio')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jardinesapp.categoria')),
            ],
        ),
    ]
